name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    strategy:
      matrix:
        target: [x86_64-linux, aarch64-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build Dtarget=${{matrix.target}} -Doptimize=ReleaseSmall
      - uses: actions/upload-artifact@v4
        with:
          name: zig-out-${{matrix.target}}
          path: zig-out
  build-darwin:
    strategy:
      matrix:
        target: [x86_64-macos, aarch64-macos]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build Dtarget=${{matrix.target}} -Doptimize=ReleaseSmall
      - uses: actions/upload-artifact@v4
        with:
          name: zig-out-${{matrix.target}}
          path: zig-out
  build-windows:
    strategy:
      matrix:
        target: [x86_64-windows]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build Dtarget=${{matrix.target}} -Doptimize=ReleaseSmall
      - uses: actions/upload-artifact@v4
        with:
          name: zig-out-${{matrix.target}}
          path: zig-out
